version: 2.1
orbs:
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      - cypress/install
      - cypress/run:
          name: Chrome
          requires:
            - cypress/install
          executor: cypress/browsers-chrome73-ff68
          record: false
          command: |
            npm run test:chrome
            npm run npm run cypress:report
            echo "command to send the report to email/slack"
          parallel: true
          parallelism: 2
          group: chrome
          browser: chrome

      - cypress/run:
          name: Firefox
          requires:
            - cypress/install
          executor: cypress/browsers-chrome73-ff68
          record: false
          command: |
            npm run test:firefox
            npm run cypress:report
            echo "command to send the report to email/slack"
          parallel: true
          parallelism: 2
          group: firefox
          browser: firefox
